line-length = 88

select = [
    'F', 'E', 'W', 'UP',
    'I', 'YTT', 'S', 'B',
    'COM', 'C4', 'SIM',
]
ignore = [
    'E501', 'E741', 'E402',
    'S101', 'S102', 'S105', 'S301', 'S311',
    'C408',
    'SIM115', 'SIM114',
]
exclude = ['tatsu/bootstrap.py']

target-version = 'py312'

[per-file-ignores]

[mccabe]
# Unlike Flake8, default to a complexity level of 10.
max-complexity = 10

[pydocstyle]
convention = 'numpy'
