# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.8
      - test-3.7
      - test-3.6
      - test-3.5

jobs:
  test-3.7:  &test-template
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:3.7

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-test.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            flake8
            py.test

      - store_artifacts:
          path: test-reports
          destination: test-reports

  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.0a3

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5


  test-pypy3  :
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo-pypy3

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo add-apt-repository ppa:pypy/ppa
            sudo apt update
            sudo apt install -y python-pip
            sudo apt install -y virtualenv
            sudo apt install -y pypy3
            virtualenv venv -p pypy3
            . venv/bin/activate
            pip install -U pip
            pip install -r requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-test.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            py.test

      - store_artifacts:
          path: test-reports
          destination: test-reports
