# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

workflows:
  version: 2
  test:
    jobs:
      - test-3.8

jobs:
  test-3.8:  &test-template
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements-test.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            sudo apt update
            sudo apt install -y python-pip
            sudo apt install -y virtualenv
            sudo apt install -y pandoc
            python -m venv venv || virtualenv venv
            . venv/bin/activate
            pip install -U pip
            pip install -Ur requirements-test.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements-test.txt" }}

      - run:
          name: test
          command: |
            . venv/bin/activate
            make test
            make examples

      - run:
          name: package
          command: |
            make distributions

      - store_artifacts:
          path: test-reports
          destination: test-reports
